/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,
  eslint: {
    ignoreDuringBuilds: false,
  },
  images: { unoptimized: true },
  async redirects() {
    return [
      { source: '/guides/beginner-guide.html', destination: '/', statusCode: 301 },
      { source: '/guides/multiplayer.html', destination: '/multiplayer/', statusCode: 301 },
      { source: '/guides/system-requirements.html', destination: '/', statusCode: 301 },
      { source: '/guides/first-hour.html', destination: '/islands/lighthouse/', statusCode: 301 },
      { source: '/guides/solo-guide.html', destination: '/walkthrough/', statusCode: 301 },
      { source: '/guides/troubleshooting.html', destination: '/fixes/', statusCode: 301 },
      { source: '/guides/achievements.html', destination: '/achievements/', statusCode: 301 },
      { source: '/guides/controls.html', destination: '/tips/', statusCode: 301 },
      { source: '/guides/progression.html', destination: '/walkthrough/', statusCode: 301 },
      { source: '/guides/how-to-fish.html', destination: '/tips/', statusCode: 301 },
      { source: '/guides/money-and-gambling.html', destination: '/tips/', statusCode: 301 },
      { source: '/wiki/fish.html', destination: '/fish/', statusCode: 301 },
      { source: '/wiki/weapons.html', destination: '/tips/', statusCode: 301 },
      { source: '/wiki/bosses.html', destination: '/bosses/', statusCode: 301 },
      { source: '/wiki/islands.html', destination: '/islands/', statusCode: 301 },
      { source: '/faq.html', destination: '/#faq', statusCode: 301 },
      { source: '/about.html', destination: '/about/', statusCode: 301 },
      { source: '/contact.html', destination: '/contact/', statusCode: 301 },
      { source: '/privacy.html', destination: '/privacy-policy/', statusCode: 301 },
      { source: '/disclaimer.html', destination: '/terms/', statusCode: 301 },
      { source: '/media', destination: '/', statusCode: 301 },
      { source: '/wiki', destination: '/', statusCode: 301 },
      { source: '/guide', destination: '/', statusCode: 301 },
      { source: '/guides', destination: '/walkthrough/', statusCode: 301 },
      { source: '/guides/:path*', destination: '/walkthrough/', statusCode: 301 },
      { source: '/gear', destination: '/fish/', statusCode: 301 },
      { source: '/gambling', destination: '/tips/', statusCode: 301 },
      { source: '/calculator', destination: '/tips/', statusCode: 301 },
      { source: '/checklist', destination: '/achievements/', statusCode: 301 },
      { source: '/codes', destination: '/tips/', statusCode: 301 },
      { source: '/maps', destination: '/islands/', statusCode: 301 },
      { source: '/map', destination: '/islands/', statusCode: 301 },
      { source: '/entities/verity', destination: '/bosses/', statusCode: 301 },
      { source: '/entities/bosses', destination: '/bosses/', statusCode: 301 },
      { source: '/weapons', destination: '/tips/', statusCode: 301 },
      { source: '/updates', destination: '/', statusCode: 301 },
      { source: '/community', destination: '/multiplayer/', statusCode: 301 },
      { source: '/tools', destination: '/tips/', statusCode: 301 },
      { source: '/privacy', destination: '/privacy-policy/', statusCode: 301 },
    ];
  },
};

module.exports = nextConfig;
