import type { Creature } from './types';

export const creatures: Creature[] = [
  { id: 'spider-crab', name: 'Spider Crab', type: 'boss', firstAvailableArea: 'Lighthouse', observedAreas: ['Lighthouse'], questUse: 'Opening-area progression lead', importantDrop: 'Keep the quest drop until the Lighthouse hand-in is complete', collectorRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'Route detail is community-sourced and should be checked against the current objective text.' },
  { id: 'leech', name: 'Leech', type: 'normal', firstAvailableArea: 'Forest', observedAreas: ['Forest'], questUse: 'Forest dinner and progression lead', hasDripVariant: true, collectorRequired: true, fishipediaRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'Use the current lure and rod prompts rather than assuming an island-exclusive spawn.' },
  { id: 'giant-piranha', name: 'Giant Piranha', type: 'boss', firstAvailableArea: 'Forest', observedAreas: ['Forest'], questUse: 'Forest major encounter', importantDrop: 'Do not sell a quest-marked drop before the hand-in', collectorRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25' },
  { id: 'endangered-fish', name: 'Endangered Fish quest target', type: 'normal', firstAvailableArea: 'Desert', observedAreas: ['Desert'], questUse: 'Desert quest lead that awards the next bait', collectorRequired: false, sourceLevel: 'unconfirmed', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'The exact creature name is intentionally withheld until confirmed in-game.' },
  { id: 'pufferfish', name: 'Pufferfish', type: 'boss', lure: 'Carrot bait (community route)', firstAvailableArea: 'Desert', observedAreas: ['Desert'], questUse: 'Desert major encounter', collectorRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'Patch 1.0.4 nerfed the encounter; exact health and damage are difficulty-dependent and unpublished.' },
  { id: 'tuna', name: 'Tuna', type: 'normal', firstAvailableArea: 'Rocks', observedAreas: ['Rocks'], questUse: 'Community-reported trigger item for the Terrorizing Bird route', hasDripVariant: true, collectorRequired: true, fishipediaRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25' },
  { id: 'terrorizing-bird', name: 'Terrorizing Bird', type: 'boss', firstAvailableArea: 'Rocks', observedAreas: ['Rocks'], questUse: 'Story encounter tied to the official Terrorizing bird achievement', collectorRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'The achievement confirms the encounter; exact combat steps remain community-sourced.' },
  { id: 'bowhead-whale', name: 'Bowhead Whale', type: 'boss', firstAvailableArea: 'Volcano', observedAreas: ['Volcano'], questUse: 'Final-island quest and boss-route requirement', importantDrop: 'Keep the quest-marked creature or drop until the final sequence is complete', collectorRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'Patch 1.0.4 nerfed the whale; the current difficulty setting changes combat values.' },
  { id: 'mutated-bowhead-whale', name: 'Mutated Bowhead Whale', type: 'boss', firstAvailableArea: 'Volcano', observedAreas: ['Volcano'], questUse: 'Final boss and Handyman target', importantDrop: 'Keep the final quest drop for the last hand-in', collectorRequired: true, sourceLevel: 'community', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'The official Handyman achievement confirms a final boss; trigger and phase guidance remain version-sensitive.' },
  { id: 'seagull', name: 'Seagull', type: 'normal', observedAreas: ['Multiple island areas observed in official media'], questUse: "Let me go and Everyone's dream achievements", collectorRequired: true, sourceLevel: 'official', verifiedPatch: '1.0.9', lastVerified: '2026-08-25', notes: 'Official achievements confirm seagull interactions but do not define a fixed spawn table.' },
];
