import type { GuidePage } from './types';
import { siteStatus } from './site-status';
import { innerPages } from './inner-pages';

const shared: Pick<GuidePage, 'lastUpdated' | 'verifiedPatch' | 'updateLog' | 'indexable'> = {
  lastUpdated: siteStatus.lastChecked,
  verifiedPatch: siteStatus.verifiedPatch,
  updateLog: [{ date: siteStatus.lastChecked, note: 'MVP baseline checked against the Steam store, official achievements, and current patch notes.' }],
  indexable: true,
};

const page = (input: Omit<GuidePage, keyof typeof shared>): GuidePage => ({ ...input, ...shared });

const corePages: GuidePage[] = [
  page({
    route: '/', priority: 'P0', pageType: 'guide-wiki-hub', primaryKeyword: 'how to fish game guide', secondaryKeywords: ['how to fish game wiki', 'how to fish guide', 'how to fish wiki', 'how to fish game', 'how to fish steam guide'],
    title: 'How to Fish Game Guide – Walkthrough, Bosses & All Islands', description: 'The complete How to Fish game guide: full walkthrough, all 5 island routes, boss strategies, fish & bait data, all 28 achievements, and patch fixes.', h1: 'How to Fish Game Guide and Wiki', eyebrow: "Dazed Games' How to Fish on Steam",
    quickAnswer: 'Start with the full walkthrough if you do not know what to do next. Use Islands for unlock order, Bosses for triggers and drops, Fish for lure and rod checks, Achievements for the 28-item route, and Fixes or Multiplayer when the game—not progression—is blocking you.',
    contentStatus: 'current', spoilerLevel: 'minor', image: '/assets/how-to-fish/hero-island-v2.webp', imageAlt: 'Castaway fishing beside a washed-up boat on a tropical island in How to Fish',
    keyFacts: [{ label: 'Current patch', value: siteStatus.verifiedPatch }, { label: 'Released', value: 'August 20, 2026' }, { label: 'Achievements', value: '28 on Steam' }, { label: 'Core co-op', value: '1–4 players' }],
    sections: [
      { id: 'status', title: 'Current game status', paragraphs: [`Patch ${siteStatus.verifiedPatch} is the verification baseline. It added limited dropped-item persistence, water cleaning for cooked tools, and more cautiously worded loading fixes. Easy/Hard and the Steam Relay diagnostic remain from Patch 1.0.9; none of these notes guarantees recovery.`] },
      { id: 'stuck', title: 'Where are you stuck?', bullets: ['No next objective: open the walkthrough.', 'No next island: check the island order and quest gate.', 'Boss will not spawn: check quest stage, bait, rod, NPC dialogue, and active encounters.', 'Fish will not bite: check reel timing, lure, and rod.', 'Save or join problem: use the status-led troubleshooting pages.'] },
      { id: 'quick-start', title: 'How to Fish quick start: your first five decisions', intro: 'This How to Fish game guide starts with five early-game decisions: follow the current objective, learn the cast-and-reel loop, keep quest catches, upgrade the next blocker, and confirm the Lighthouse hand-in before sailing toward Forest.', steps: [
        `Learn the basic cast-and-reel loop before chasing rare catches. Equip the rod and lure or bait shown by the game, cast at the active spot, then follow the bite and reeling prompts. Platform controls may differ, so use the on-screen input.`,
        `Sell ordinary catches only after checking the active request. Keep any named or quest-marked creature or drop until the hand-in advances. Use early income on the limitation blocking progress instead of gambling valuable catches or buying optional gear.`,
        `Upgrade for the next problem. Fishing equipment and inventory space support the opening loop; healing or combat equipment matters when a boss gate becomes active. Keep a coin buffer instead of following an unverified fixed-price build.`,
        `Treat Radar as direction and the objective log as the progress check. Before leaving an area, finish the relevant NPC dialogue, confirm any required item remains in inventory, and make sure the next route or marker has appeared.`,
        `If fish stop biting after the opening island, check the equipped lure, rod, reel timing, and quest stage before assuming a bug. Use the fish database or tips page for version-sensitive details instead of treating one community report as universal.`,
      ] },
      { id: 'fishing-basics', title: 'How to cast, catch, and prepare for a boss', paragraphs: [
        'A safe trip has three phases: prepare, fish, and return. Read the objective, equip the requested rod and lure or bait, and leave space for a quest catch. Cast, wait for the bite cue, follow the current reeling interaction, then return when the objective or inventory shows the trip is complete.',
        'Before a boss encounter, confirm the quest stage, required item, NPC dialogue, and replaceable supplies. During the fight, favor readable attack windows and room to retreat. If the encounter does not appear, recheck the stage, equipment, and active encounters. Exact health, damage, and timing values remain unconfirmed.',
      ] },
      { id: 'lighthouse-chapter', title: 'Chapter 1: Lighthouse to the first boss', intro: 'The Lighthouse is the starting area and teaches the game’s core progression loop. This is a community-documented chapter summary, so use the current objective as the authority when wording or trigger timing differs.', paragraphs: [
        `Follow the opening NPC dialogue before travelling toward every visible point of interest. Investigate the local request, fish with the equipment currently available, return the relevant result, and read the next instruction. A Radar marker gives direction; it does not prove that dialogue, an encounter, or a hand-in is complete. Pause when the objective changes so you do not mistake a travel task for a catch or encounter.`,
        `Use the first catches to learn the bite cue and reeling interaction. The goal is a reliable catch-and-sell loop, not an unverified species table. Sell ordinary catches, improve the equipment that is actually limiting progress, and keep room for anything named by the active request.`,
        `Do not sell a creature or drop the request may need. Spider Crab is retained here as a community-documented lead for the opening boss gate, not as a verified lure, bait, or Lighthouse-exclusive spawn. If the name or trigger differs in your build, follow the current game text and keep the relevant result after the encounter.`,
        `Before the first boss, complete the related dialogue, confirm the quest stage, equip the required fishing and combat gear, and carry supplies you can safely replace. If the encounter does not appear, recheck the stage, required catch, NPC, equipment, and other active encounters before treating the save as broken. Use the dedicated boss and fixes pages for deeper troubleshooting.`,
        `After the encounter, keep the quest-marked result until the hand-in clearly advances. Confirm that Boat Keys or the next route instruction is available before selling spare catches or reorganizing the inventory. Then use the updated objective and Radar to identify the Forest route. Continue with the full walkthrough for every chapter or the island guides for focused preparation and version-sensitive notes.`,
      ] },
      { id: 'next-steps', title: 'What to do after Lighthouse', paragraphs: ['The broad route is Lighthouse → Forest → Desert → Rocks → Volcano. Complete each local request, encounter, and hand-in before following the next Radar route. Keep an uncertain quest creature until the objective advances. Use the full walkthrough for the complete story sequence, island guides for preparation, boss guides for encounter blockers, and the fish database for rod, lure, and area checks.'] },
      { id: 'verification', title: 'How this wiki verifies claims', paragraphs: ['Official store, patch, and achievement text is labelled Official. Repeatable current-build observations are Verified In-Game. Forum, Reddit, video, and third-party route details remain Community or Unconfirmed until repeated. When guidance conflicts, follow the current objective and patch rather than forced certainty.'] },
    ],
    faqs: [{ question: 'What should I do first in How to Fish?', answer: 'Follow the opening objective, learn a reliable catch-and-sell loop, and use the walkthrough when the next quest or island gate is unclear.' }, { question: 'How many achievements are there?', answer: 'Steam currently lists 28 achievements.' }],
    relatedPages: ['/walkthrough/', '/islands/', '/bosses/mutated-bowhead-whale/', '/achievements/', '/fixes/'], sources: ['steamStore', 'steamAchievements', 'patch110', 'patch109', 'communityGuide', 'islandsGuide'],
  }),
  page({
    route: '/walkthrough/', priority: 'P1', pageType: 'walkthrough', primaryKeyword: 'how to fish game walkthrough', secondaryKeywords: ['how to fish walkthrough', 'how to fish full walkthrough', 'how to beat how to fish game', 'how to fish story guide'],
    title: 'How to Fish Game Walkthrough: Full Story & All Islands', description: 'Follow the full route from the Lighthouse to the Volcano, including every quest gate, boss trigger, item hand-in, island unlock, and the ending.', h1: 'How to Fish Game Walkthrough', eyebrow: 'FULL STORY ROUTE',
    quickAnswer: 'The community-documented main route is Lighthouse → Forest → Desert → Rocks → Volcano. Finish each local NPC request, obtain the encounter trigger, defeat the major creature, keep the quest-marked result, complete the hand-in, and then follow the new Radar route. Patch 1.0.5 removed the old skip-any-island shortcut.',
    contentStatus: 'version-sensitive', spoilerLevel: 'full', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition travelling between tropical islands',
    keyFacts: [{ label: 'Route', value: 'Lighthouse → Volcano' }, { label: 'Areas', value: 'Start + 4 unlocks' }, { label: 'Skip status', value: 'Closed in 1.0.5' }, { label: 'Spoilers', value: 'Full story' }],
    sections: [
      { id: 'before', title: 'Before you start', bullets: ['Back up the save before experimenting with community workarounds.', 'Do not sell quest-marked creatures or boss drops before the related hand-in.', 'Use Radar markers as direction, not proof that a quest gate is complete.', 'Recheck equipment after each island unlock.'] },
      { id: 'lighthouse', title: 'Chapter 1: Lighthouse', steps: ['Follow the keeper and opening objectives.', 'Use the Radar and current objective text to identify the Spider Crab lead.', 'Keep the quest result until the keeper advances the route.', 'Confirm that the boat-key objective and Forest route appear before leaving.'] },
      { id: 'forest', title: 'Chapter 2: Forest', steps: ['Complete the dinner request associated with three leeches.', 'Confirm the current boss-bait prompt.', 'Defeat the Giant Piranha encounter and keep the quest drop.', 'Complete the hand-in and confirm the Desert destination.'] },
      { id: 'desert', title: 'Chapter 3: Desert', steps: ['Complete the endangered-creature request.', 'Receive and equip the current carrot-bait lead.', 'Fight the Pufferfish on your selected difficulty.', 'Return the required result and confirm the Rocks route.'] },
      { id: 'rocks', title: 'Chapter 4: Rocks', steps: ['Follow the Tuna quest lead.', 'Trigger the Terrorizing Bird sequence only after the local NPC dialogue is complete.', 'Use terrain for cover and keep the next-route item.', 'Confirm the Volcano coordinates before departing.'] },
      { id: 'volcano', title: 'Chapter 5: Volcano', steps: ['Complete the military and scientist objectives shown in the current build.', 'Secure the Bowhead Whale requirement without selling the quest-marked result.', 'Use the final-boss guide for the Mutated Bowhead Whale sequence.', 'Complete the last hand-in and ending route.'] },
      { id: 'blockers', title: 'Common progression blockers', bullets: ['Boss absent: recheck dialogue, bait, rod, quest stage, and whether another encounter remains active.', 'NPC stalled: return with the marked item in inventory and re-enter the area.', 'Radar missing or inventory changed after loading: stop overwriting the only save and open the fixes page.'] },
    ],
    faqs: [{ question: 'Can I travel to later islands early?', answer: 'Patch 1.0.5 fixed the bug that allowed travel to any island without unlocking it, so current routes should follow the intended gates.' }, { question: 'Should I sell boss drops?', answer: 'Not until the related NPC hand-in is complete and the next route is confirmed.' }],
    relatedPages: ['/islands/', '/islands/lighthouse/', '/islands/forest/', '/islands/desert/', '/islands/rocks/', '/islands/volcano/', '/bosses/mutated-bowhead-whale/'], sources: ['steamStore', 'patch105', 'communityGuide', 'islandsGuide'],
  }),
  page({
    route: '/islands/', priority: 'P1', pageType: 'island-hub', primaryKeyword: 'how to fish game all islands', secondaryKeywords: ['how to fish all islands', 'how to fish island order', 'how to unlock islands in how to fish', 'how to fish island locations'],
    title: 'How to Fish Game: All Islands, Order & Unlocks', description: 'See the Lighthouse and four unlockable islands in order, with Radar routes, unlock requirements, main quests, bosses, and links to each area guide.', h1: 'All Islands and Areas in How to Fish', eyebrow: 'ISLAND ROUTE',
    quickAnswer: 'Count the route as one starting Lighthouse area plus four unlockable island areas: Forest, Desert, Rocks, and Volcano. Complete the local request and major encounter, preserve the important hand-in, then use the updated Radar route. This wording reconciles “five areas” with “four unlockable islands.”',
    contentStatus: 'version-sensitive', spoilerLevel: 'full', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition across a chain of tropical islands',
    keyFacts: [{ label: 'Starting area', value: 'Lighthouse' }, { label: 'Unlockable areas', value: '4' }, { label: 'Final area', value: 'Volcano' }, { label: 'Route gate', value: 'Quest + encounter' }],
    sections: [
      { id: 'count', title: 'How many islands are there?', paragraphs: ['Players often say five islands, while route guides describe four islands after the Lighthouse start. This page uses “starting area plus four unlockable areas” so the count and progression model are both clear.'] },
      { id: 'order', title: 'Island order', steps: ['Lighthouse — opening keeper route and Spider Crab lead.', 'Forest — dinner request and Giant Piranha lead.', 'Desert — endangered-creature request and Pufferfish lead.', 'Rocks — Tuna route and Terrorizing Bird encounter.', 'Volcano — military/scientist objectives, whale route, and ending.'] },
      { id: 'unlock', title: 'How island progression works', bullets: ['Finish the NPC request shown in the current objective log.', 'Use the requested creature, lure, or quest item.', 'Complete the major encounter.', 'Keep and hand in the required result.', 'Follow the new Radar destination only after the hand-in advances.'] },
      { id: 'radar', title: 'Radar route and marker guide', paragraphs: ['A marker points you toward an objective or destination; it does not bypass a missing hand-in. If the next area is absent, return to the relevant NPC, check inventory, and confirm no active boss remains.'] },
    ],
    faqs: [{ question: 'Are there four or five islands?', answer: 'The clearest current wording is a starting Lighthouse area plus four unlockable areas.' }, { question: 'Why is the next island missing?', answer: 'A quest, boss trigger, item hand-in, or NPC dialogue step is usually incomplete; Patch 1.0.5 also closed the old travel skip.' }],
    relatedPages: ['/walkthrough/', '/islands/lighthouse/', '/islands/forest/', '/islands/desert/', '/islands/rocks/', '/islands/volcano/'], sources: ['steamStore', 'patch105', 'islandsGuide', 'communityGuide'],
  }),
  page({
    route: '/islands/lighthouse/', priority: 'P2', pageType: 'island-guide', primaryKeyword: 'how to fish game lighthouse', secondaryKeywords: ['how to fish lighthouse guide', 'how to fish game boat keys', 'how to fish game spider crab', 'how to get radar how to fish game'],
    title: 'How to Fish Lighthouse Guide: Spider Crab & Boat Keys', description: 'Escape the starting Lighthouse area: get the Radar, catch the Spider Crab, keep its shell, receive the boat keys, and reach the Forest.', h1: 'How to Fish Lighthouse and Spider Crab Guide', eyebrow: 'AREA 01 · START',
    quickAnswer: 'Use the Lighthouse keeper and current objective text to establish the opening route, locate the Spider Crab lead with the Radar, and keep the quest-marked result until the hand-in is complete. Confirm the boat-key objective and Forest destination before leaving; exact prompt wording may differ by patch.',
    contentStatus: 'version-sensitive', spoilerLevel: 'minor', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition near a tropical lighthouse island',
    keyFacts: [{ label: 'Order', value: 'Starting area' }, { label: 'Major lead', value: 'Spider Crab' }, { label: 'Keep', value: 'Quest-marked result' }, { label: 'Next', value: 'Forest' }],
    sections: [
      { id: 'unlock', title: 'How to start the Lighthouse route', steps: ['Speak with the keeper and read the current objective.', 'Locate and understand the Radar marker.', 'Check the live shop before spending the full first haul.'] },
      { id: 'progression', title: 'Step-by-step progression', steps: ['Complete the opening catch-and-sell instruction.', 'Follow the community-documented Spider Crab lead.', 'Keep the marked result in inventory.', 'Return to the keeper and exhaust the relevant dialogue.'] },
      { id: 'encounter', title: 'Spider Crab and the important item', paragraphs: ['The encounter is a progression lead rather than a standalone boss page in the MVP. Do not publish health, damage, or a fixed bait claim until the current build is checked directly.'] },
      { id: 'next', title: 'How to reach the Forest', paragraphs: ['Only depart after the hand-in advances, the boat-key objective is resolved, and the Radar shows the next destination. If it does not, reload cautiously and consult the fixes page before overwriting the only save.'] },
    ],
    faqs: [{ question: 'Where do I get the Radar?', answer: 'Follow the opening Lighthouse keeper objectives; the exact interaction wording remains version-sensitive.' }, { question: 'Why did the Forest not unlock?', answer: 'Recheck the Spider Crab-related hand-in, keeper dialogue, and boat-key objective.' }],
    relatedPages: ['/islands/', '/walkthrough/', '/bosses/', '/fish/', '/islands/forest/'], sources: ['steamStore', 'islandsGuide', 'communityGuide'],
  }),
  page({
    route: '/islands/forest/', priority: 'P2', pageType: 'island-guide', primaryKeyword: 'how to fish game forest island', secondaryKeywords: ['how to fish forest guide', 'how to get leeches how to fish game', 'how to fish giant piranha', 'how to fish dinnertime achievement'],
    title: 'How to Fish Forest Guide: Leeches & Giant Piranha', description: 'Find three leeches, obtain the boss bait, defeat the Giant Piranha, return its quest drop, and unlock the Desert island route.', h1: 'How to Fish Forest and Giant Piranha Guide', eyebrow: 'AREA 02 · FOREST',
    quickAnswer: 'In the Forest, follow the local dinner request associated with three leeches, confirm the current bait or trigger prompt, complete the Giant Piranha encounter, and keep the quest-marked result for its hand-in. The official Dinnertime achievement confirms the Forest dinner objective; lure details remain community-sourced.',
    contentStatus: 'version-sensitive', spoilerLevel: 'minor', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fisher reeling in a colorful fish near forest islands',
    keyFacts: [{ label: 'Order', value: 'Second area' }, { label: 'Quest lead', value: 'Three leeches' }, { label: 'Encounter', value: 'Giant Piranha' }, { label: 'Next', value: 'Desert' }],
    sections: [
      { id: 'arrive', title: 'What to do on arrival', bullets: ['Read the Forest NPC objective before fishing.', 'Keep one free inventory slot for quest items.', 'Carry recoverable healing and a weapon appropriate to your selected difficulty.'] },
      { id: 'leeches', title: 'Three leeches and Dinnertime', paragraphs: ['Steam officially confirms an achievement for catching dinner for the lady in the Forest. Community routes identify three leeches; confirm the live counter and wording before treating that count as permanent.'] },
      { id: 'piranha', title: 'Giant Piranha encounter', steps: ['Finish the dinner dialogue.', 'Equip the lure/rod shown by the current quest and shop.', 'Trigger the encounter and learn its current attack windows.', 'Keep the quest-marked result after the fight.'] },
      { id: 'next', title: 'Unlock the Desert route', paragraphs: ['Return the required result, exhaust dialogue, and confirm the Desert marker. If no route appears, check for an incomplete dinner objective or an encounter still active.'] },
    ],
    faqs: [{ question: 'How do I unlock Dinnertime?', answer: 'Complete the Forest dinner request; the official achievement does not specify every route step.' }, { question: 'Why will the Giant Piranha not spawn?', answer: 'Confirm the NPC stage, bait, rod, and whether the dinner objective is complete.' }],
    relatedPages: ['/islands/', '/walkthrough/', '/bosses/', '/fish/', '/islands/lighthouse/', '/islands/desert/', '/achievements/#dinnertime'], sources: ['steamAchievements', 'communityGuide', 'islandsGuide'],
  }),
  page({
    route: '/islands/desert/', priority: 'P2', pageType: 'island-guide', primaryKeyword: 'how to fish game desert island', secondaryKeywords: ['how to fish desert guide', 'how to fish pufferfish', 'how to fish carrot bait', 'how to fish endangered fish'],
    title: 'How to Fish Desert Guide: Pufferfish & Carrot Bait', description: 'Complete the endangered-fish quest, get the carrot bait, defeat the Pufferfish, return its drop, and unlock the Rocks route.', h1: 'How to Fish Desert and Pufferfish Guide', eyebrow: 'AREA 03 · DESERT',
    quickAnswer: 'Complete the Desert NPC request for the current endangered-creature target, verify the awarded carrot-bait lead in your objective log, then prepare for the Pufferfish encounter on your selected difficulty. Patch 1.0.4 nerfed Pufferfish, so older combat numbers and timings should not be copied forward.',
    contentStatus: 'version-sensitive', spoilerLevel: 'minor', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition approaching a sunny desert island',
    keyFacts: [{ label: 'Order', value: 'Third area' }, { label: 'Quest lead', value: 'Endangered target' }, { label: 'Encounter', value: 'Pufferfish' }, { label: 'Patch note', value: 'Nerfed in 1.0.4' }],
    sections: [
      { id: 'prepare', title: 'Prepare for the Desert', bullets: ['Read the endangered-creature objective exactly.', 'Do not assume a community creature nickname is the current quest name.', 'Carry healing and enough ammunition to learn the encounter.'] },
      { id: 'carrot', title: 'Endangered target and carrot bait', paragraphs: ['Community routes connect the request to carrot bait. Confirm the reward and equip it from the current build rather than buying or discarding items based on an old table.'] },
      { id: 'pufferfish', title: 'Pufferfish strategy', steps: ['Trigger the encounter only after the related dialogue.', 'Keep distance from the body and use clear damage windows.', 'Adjust expectations for Easy, Default, or Hard health and damage.', 'Preserve the quest-marked result.'] },
      { id: 'next', title: 'Unlock the Rocks route', paragraphs: ['Complete the required hand-in and wait for the objective/Radar update. A missing marker usually means the quest stage or dialogue did not advance.'] },
    ],
    faqs: [{ question: 'Was Pufferfish changed?', answer: 'Yes. Patch 1.0.4 says Pufferfish was nerfed, but it does not publish exact values.' }, { question: 'Where does carrot bait come from?', answer: 'Community routes tie it to the Desert request; verify the current objective and reward in-game.' }],
    relatedPages: ['/islands/', '/walkthrough/', '/bosses/', '/fish/', '/islands/forest/', '/islands/rocks/'], sources: ['patch104', 'communityGuide', 'islandsGuide'],
  }),
  page({
    route: '/islands/rocks/', priority: 'P2', pageType: 'island-guide', primaryKeyword: 'how to fish game rocks island', secondaryKeywords: ['how to fish rocks guide', 'how to fish tuna', 'how to fish terrorizing bird', 'how to fish albatross boss'],
    title: 'How to Fish Rocks Guide: Tuna & Terrorizing Bird', description: 'Catch the Tuna, use it to trigger the Terrorizing Bird, fight from cover, collect the reward, and unlock the Volcano area.', h1: 'How to Fish Rocks and Terrorizing Bird Guide', eyebrow: 'AREA 04 · ROCKS',
    quickAnswer: 'On Rocks, complete the local dialogue before following the Tuna trigger lead, then use terrain and cover for the Terrorizing Bird encounter. Steam confirms a Terrorizing bird achievement, while the Tuna trigger and exact combat route remain community-sourced. Keep the resulting quest item until Volcano unlocks.',
    contentStatus: 'version-sensitive', spoilerLevel: 'minor', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition approaching rocky tropical islands',
    keyFacts: [{ label: 'Order', value: 'Fourth area' }, { label: 'Trigger lead', value: 'Tuna' }, { label: 'Encounter', value: 'Terrorizing Bird' }, { label: 'Next', value: 'Volcano' }],
    sections: [
      { id: 'arrive', title: 'Rocks preparation', bullets: ['Bring a weapon you can replace after a failed attempt.', 'Identify hard cover before the encounter begins.', 'Complete the scared-islander dialogue before using the trigger.'] },
      { id: 'tuna', title: 'Tuna trigger lead', paragraphs: ['Treat Tuna as a community-documented route lead, not a universal island-only spawn. Check the current lure, rod, and quest prompt before fishing.'] },
      { id: 'bird', title: 'Fight the Terrorizing Bird', steps: ['Start from cover and observe its approach.', 'Damage during safe windows instead of chasing over open ground.', 'Use healing after creating distance.', 'Collect and preserve any quest-marked result.'] },
      { id: 'next', title: 'Unlock Volcano', paragraphs: ['Finish the local hand-in and confirm the final route in the objective log and Radar. Patch 1.0.4 made the intended path to the final island easier to see.'] },
    ],
    faqs: [{ question: 'Is Terrorizing Bird an official achievement?', answer: 'Yes. Steam lists an achievement for defending the islanders from it.' }, { question: 'Why can I not see the Volcano route?', answer: 'Complete the Rocks hand-in and check the updated Radar; Patch 1.0.4 improved the intended path visibility.' }],
    relatedPages: ['/islands/', '/walkthrough/', '/bosses/', '/fish/', '/islands/desert/', '/islands/volcano/', '/achievements/#terrorizing-bird'], sources: ['steamAchievements', 'patch104', 'communityGuide'],
  }),
  page({
    route: '/islands/volcano/', priority: 'P2', pageType: 'island-guide', primaryKeyword: 'how to fish game volcano island', secondaryKeywords: ['how to fish volcano guide', 'how to fish military island', 'how to fish bowhead whale', 'how to fish final island'],
    title: 'How to Fish Volcano Guide: Bowhead Whale & Ending', description: 'Complete the military and scientist quests, catch the Bowhead Whale, trigger the Mutated Bowhead Whale, and finish the final escape.', h1: 'How to Fish Volcano and Bowhead Whale Guide', eyebrow: 'AREA 05 · VOLCANO',
    quickAnswer: 'Treat Volcano as the final progression area: finish the current military and scientist objectives, secure the Bowhead Whale requirement, and keep all quest-marked results until the final sequence and hand-in are complete. Patch 1.0.4 nerfed Whale; use the dedicated final-boss page for the version-sensitive Mutated Bowhead Whale route.',
    contentStatus: 'version-sensitive', spoilerLevel: 'full', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition heading toward a volcanic island',
    keyFacts: [{ label: 'Order', value: 'Final area' }, { label: 'Quest groups', value: 'Military + scientist' }, { label: 'Requirement', value: 'Bowhead Whale lead' }, { label: 'Final boss', value: 'Separate guide' }],
    sections: [
      { id: 'arrive', title: 'What to finish before the final route', bullets: ['Confirm both military and scientist objectives.', 'Carry recoverable healing and ammunition.', 'Choose Easy, Default, or Hard before planning boss timing.'] },
      { id: 'military', title: 'Military and scientist objectives', paragraphs: ['The official Deadliest catch achievement confirms a military objective involving a large creature. The exact scientist request sequence remains community-documented and should be checked against current dialogue.'] },
      { id: 'whale', title: 'Bowhead Whale requirement', steps: ['Read the active objective before fishing.', 'Use the current rod and lure prompt.', 'Do not sell the quest-marked result.', 'Move to the final trigger only after the objective advances.'] },
      { id: 'ending', title: 'Final boss and ending hand-in', paragraphs: ['Open the Mutated Bowhead Whale guide for trigger, fight, Handyman, and post-fight steps. Keep this island page focused on the Volcano quest topology.'] },
    ],
    faqs: [{ question: 'Was Whale changed?', answer: 'Patch 1.0.4 says Whale was nerfed; exact combat values are not published in the patch note.' }, { question: 'Where is the full final-boss strategy?', answer: 'Use the dedicated Mutated Bowhead Whale page so the island route and boss intent do not duplicate each other.' }],
    relatedPages: ['/islands/', '/walkthrough/', '/bosses/', '/fish/', '/islands/rocks/', '/bosses/mutated-bowhead-whale/'], sources: ['steamAchievements', 'patch104', 'communityGuide', 'islandsGuide'],
  }),
  page({
    route: '/bosses/', priority: 'P1', pageType: 'boss-hub', primaryKeyword: 'how to fish game boss', secondaryKeywords: ['how to fish game bosses', 'how to fish all bosses', 'how to fish boss bait', 'how to fish boss locations'],
    title: 'How to Fish Game Boss Guide: All Bosses & Bait', description: 'Find every verified story and optional boss, its lure or quest trigger, recommended weapons, fight tips, important drops, and the next step.', h1: 'All Bosses in How to Fish', eyebrow: 'BOSS ROUTE',
    quickAnswer: 'Story encounters follow the island route from the Spider Crab lead through Giant Piranha, Pufferfish, Terrorizing Bird, Bowhead Whale, and the final Mutated Bowhead Whale sequence. Verify the current quest stage, bait, rod, NPC dialogue, and active encounter before assuming a boss is bugged; difficulty now changes health and damage.',
    contentStatus: 'version-sensitive', spoilerLevel: 'full', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition crossing bright ocean between islands',
    keyFacts: [{ label: 'Difficulty', value: 'Easy / Default / Hard' }, { label: 'Main gate', value: 'Quest + trigger' }, { label: 'Drops', value: 'Keep until hand-in' }, { label: 'Final boss', value: 'Dedicated P0 guide' }],
    sections: [
      { id: 'route', title: 'Main story boss route', steps: ['Lighthouse: Spider Crab progression lead.', 'Forest: Giant Piranha encounter.', 'Desert: Pufferfish encounter.', 'Rocks: Terrorizing Bird encounter.', 'Volcano: Bowhead Whale and final mutation sequence.'] },
      { id: 'triggers', title: 'How lures and quest triggers work', paragraphs: ['A creature name alone is not enough. The current objective, NPC dialogue, lure, rod, and any existing active boss can all determine whether the encounter begins.'] },
      { id: 'difficulty', title: 'Difficulty setting effects', paragraphs: ['Patch 1.0.9 states that Easy creatures have 25% less health and deal 50% less damage; Hard creatures have 25% more health and deal 25% more damage. Default matches the previous setting.'] },
      { id: 'not-spawning', title: 'Boss not spawning checklist', bullets: ['Correct quest stage and NPC dialogue?', 'Correct lure and rod?', 'Required item still in inventory?', 'Another boss already active?', 'Host and clients on the same patch?', 'Steam Relay diagnostic normal for co-op?'] },
      { id: 'coop', title: 'Solo and co-op roles', paragraphs: ['In co-op, assign damage, small-enemy control, healing, and revive/aggro roles. The game is intended for 1–4 players even though larger lobbies are technically supported.'] },
    ],
    faqs: [{ question: 'Does difficulty change bosses?', answer: 'Patch 1.0.9 applies creature health and damage modifiers, so timings differ by setting.' }, { question: 'Why did a boss not spawn?', answer: 'Check quest stage, dialogue, bait, rod, active encounters, patch alignment, and co-op Relay status.' }],
    relatedPages: ['/walkthrough/', '/islands/', '/bosses/mutated-bowhead-whale/', '/tips/', '/multiplayer/'], sources: ['steamStore', 'patch109', 'communityGuide', 'steamAchievements'],
  }),
  page({
    route: '/bosses/mutated-bowhead-whale/', priority: 'P0', pageType: 'boss-guide', primaryKeyword: 'how to fish mutated bowhead whale', secondaryKeywords: ['how to beat mutated bowhead whale', 'how to fish final boss', 'how to summon mutated bowhead whale', 'how to fish volcanic whale', 'how to fish handyman achievement'],
    title: 'Mutated Bowhead Whale in How to Fish: Final Boss', description: 'Complete the Fish Bucket chain, throw the Bowhead Whale into the Volcano, survive the mutated fight, and finish the RHIB hand-in.', h1: 'How to Beat the Mutated Bowhead Whale in How to Fish', eyebrow: 'P0 FINAL BOSS · FULL SPOILERS',
    quickAnswer: 'Give the Volcano scientist the requested fish, use the Fish Bucket to catch and defeat the normal Bowhead Whale, then carry its body to the crater and throw it into the lava. Fight the Mutated Bowhead Whale from a compact movement loop, heal early, keep the final trophy, and return it to the scientist for the RHIB ending.',
    contentStatus: 'version-sensitive', spoilerLevel: 'full', image: '/assets/how-to-fish/steam-gear.jpg', imageAlt: 'Official How to Fish screenshot showing a prepared late-game weapon loadout',
    keyFacts: [{ label: 'Area', value: 'Volcano' }, { label: 'First trigger', value: 'Fish Bucket' }, { label: 'Final trigger', value: 'Bowhead Whale into lava' }, { label: 'After victory', value: 'Return trophy for RHIB' }],
    sections: [
      { id: 'requirements', title: 'What must be ready before the two-whale sequence?', bullets: ['Reach Volcano through the intended island order.', 'Finish the scientist request shown by the live objective.', 'Bring a sustained ranged weapon, ammunition, and replaceable healing.', 'Leave inventory space for the normal Whale and final trophy.', 'Choose the difficulty before consuming the Fish Bucket.'] },
      { id: 'first-whale', title: 'How do you obtain and preserve the normal Bowhead Whale?', paragraphs: ['Current written routes agree that the scientist trades the Fish Bucket after the Volcano fish request. Use that trigger for the normal Bowhead Whale, create distance when it launches upward, and keep the intact body after the kill. Patch 1.0.4 nerfed Whale, but no official health table was published.'] },
      { id: 'summon', title: 'How do you summon the Mutated Bowhead Whale?', steps: ['Confirm the normal Bowhead Whale body is still available.', 'Carry it up the Volcano route toward the crater.', 'Equip the body and throw it into the lava.', 'Wait for the encounter state to change.', 'Return to the compact fight area instead of escaping across open water.'] },
      { id: 'fight', title: 'Which movement loop handles the final boss?', paragraphs: ['Current route sources describe rolls, stomps, lava pools, and a more aggressive later phase. Keep the boss inside the Volcano region, strafe a compact loop with a clear escape lane, stop firing during a stomp wind-up, and heal after each damaging hit rather than waiting for critical health.'] },
      { id: 'after', title: 'What completes the ending after the boss dies?', paragraphs: ['The fight is not the last action. Pick up the distinct fin, tail, or quest-marked trophy shown by the current build, return it to the scientist, receive the RHIB keys, and use the RHIB to complete the ending. Do not sell or cook the trophy.'] },
      { id: 'handyman', title: 'How should you approach the Handyman achievement?', paragraphs: ['Steam officially requires defeating the final boss with bare hands. A final-punch-only method is a community report, not the literal requirement. Use the dedicated achievement page and a separate prepared attempt if you want the clearest evidence that every damaging action complied.'], callout: { tone: 'warning', title: 'Version-sensitive achievement', text: 'Patch 1.0.4 fixed the bare-hands achievement. Do not treat one community final-hit method as guaranteed for every player.' } },
    ],
    evidenceRows: [
      { topic: 'Final-boss identity', official: 'Steam achievements confirm the final-boss, game-completion, and bare-hands objectives.', community: 'Current walkthroughs identify the Mutated Bowhead Whale as the Volcano finale.', guidance: 'Use the official objectives for requirements and route sources for the sequence.' },
      { topic: 'Summon chain', official: 'Patch notes do not publish the Fish Bucket and lava sequence.', community: 'Independent current guides agree on scientist fish request → Fish Bucket → normal Whale → lava.', guidance: 'Follow the live objective when labels differ.' },
      { topic: 'Fight and hand-in', official: 'Difficulty modifiers are official; fixed HP and phase values are not.', community: 'Route sources describe stomp, roll, lava, trophy return, and RHIB keys.', guidance: 'Use cue-based movement and preserve the marked result.' },
    ],
    failureBranches: [
      { symptom: 'No Fish Bucket is awarded', likelyState: 'Scientist request or hand-in is incomplete', nextStep: 'Re-read the objective and finish the required fish hand-in before spending another lure.' },
      { symptom: 'Normal Whale is defeated but no final boss appears', likelyState: 'The body was not carried to and thrown into the lava trigger', nextStep: 'Recover the intact Whale and follow the crater sequence.' },
      { symptom: 'Mutated Whale vanishes or resets', likelyState: 'Fight moved too far outside the encounter area', nextStep: 'Use a tighter Volcano loop and do not interpret disappearance as victory.' },
      { symptom: 'Boss dies but ending does not start', likelyState: 'Final trophy was not returned', nextStep: 'Recover the quest-marked result, return it to the scientist, and use the RHIB.' },
    ],
    media: {
      video: { href: 'https://www.youtube.com/watch?v=615yz4UD1nM', embedUrl: 'https://www.youtube-nocookie.com/embed/615yz4UD1nM', title: 'Full-route video with the Volcano finale', description: 'Use the footage to understand sequencing and movement. Its timing and loadout are player-specific, not a guaranteed boss plan.', sourceId: 'final-boss-route-video' },
      gallery: [
        { src: '/assets/how-to-fish/steam-gear.jpg', alt: 'Official screenshot of late-game weapons and equipment in How to Fish', caption: 'Official preparation context; it does not establish a required weapon.', sourceId: 'steam-media' },
        { src: '/assets/how-to-fish/steam-quest.jpg', alt: 'Official screenshot of an NPC quest interaction in How to Fish', caption: 'Use the live scientist objective as the hand-in authority.', sourceId: 'steam-media' },
        { src: '/assets/how-to-fish/steam-catch.jpg', alt: 'Official screenshot of a creature catch near the shore in How to Fish', caption: 'Preserve named and quest-marked catches through the final sequence.', sourceId: 'steam-media' },
      ],
    },
    faqs: [{ question: 'What does Handyman officially require?', answer: 'Steam says to defeat the final boss with bare hands.' }, { question: 'Can I rely on a final-hit-only method?', answer: 'That is a community claim and remains version-sensitive; the literal official requirement is the safer route.' }],
    relatedPages: ['/', '/bosses/', '/islands/volcano/', '/walkthrough/', '/achievements/handyman/'], sources: ['steamAchievements', 'patch104', 'patch109', 'patch110', 'finalBossGuide', 'finalBossVideo', 'communityGuide', 'steamMedia'],
  }),
  page({
    route: '/achievements/', priority: 'P0', pageType: 'achievement-database', primaryKeyword: 'how to fish all achievements', secondaryKeywords: ['how to fish achievements', 'how to fish 28 achievements', 'how to fish achievement guide', 'how to fish 100 percent guide', 'how to fish bean achievement', 'how to fish handyman achievement'],
    title: 'How to Fish All Achievements: Unlock All 28', description: 'Unlock all 28 Steam achievements with a route-based checklist, current Bean warning, Handyman strategy, Collector and Fishipedia cleanup.', h1: 'All 28 How to Fish Achievements', eyebrow: '100% ROUTE · LOCAL CHECKLIST',
    quickAnswer: 'Steam lists 28 achievements. Let the story unlock natural objectives first, then clean up money and combat challenges, finish Collector and Fishipedia with the creature database, and attempt Bean on a clean current-patch route. Patch 1.0.5 removed the old skip-any-island bug, so do not use obsolete speedrun instructions.',
    contentStatus: 'version-sensitive', spoilerLevel: 'full', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition with tropical islands and a colorful catch',
    keyFacts: [{ label: 'Total', value: '28' }, { label: 'Rarest current', value: 'Bean' }, { label: 'Checklist', value: 'Saved locally' }, { label: 'Baseline', value: `Patch ${siteStatus.verifiedPatch}` }],
    sections: [
      { id: 'overview', title: 'Achievement overview', paragraphs: ['Official Steam names, descriptions, and current completion rates are shown in the checklist. Route advice is kept separate so official requirements are never silently rewritten.'] },
      { id: 'route', title: 'Recommended completion route', steps: ['Phase 1: finish natural story and island achievements.', 'Phase 2: clean up combat, equipment, cooking, and gambling challenges.', 'Phase 3: use the evidence-labelled creature table for Collector and Fishipedia.', 'Phase 4: prepare a fresh legitimate sub-one-hour Bean attempt.'] },
      { id: 'hardest', title: 'Hardest achievements', bullets: ['Bean — finish within one hour on the current route.', 'Handyman — final boss with bare hands.', 'Fishipedia — all Drip creatures.', 'Collector — all creatures.', "Everyone's dream — seagull with dynamite.", 'Rich! Millionaire — one sale worth 100,000 or more.'] },
      { id: 'warnings', title: 'Version-sensitive warnings', paragraphs: ['Patch 1.0.5 removed the skip-any-island bug and fixed Fishipedia requiring an extra Drip. Patch 1.0.4 fixed Handyman for all players. Old routes can therefore fail even when their videos still rank.'] },
    ],
    faqs: [{ question: 'How many achievements does How to Fish have?', answer: 'Steam currently lists 28.' }, { question: 'Does the old Bean island skip still work?', answer: 'Patch 1.0.5 says the travel-to-any-island bug was fixed, so build a current legitimate route instead.' }],
    relatedPages: ['/walkthrough/', '/fish/', '/bosses/mutated-bowhead-whale/', '/tips/', '/islands/'], sources: ['steamAchievements', 'patch104', 'patch105', 'beanDiscussion', 'communityGuide'],
  }),
  page({
    route: '/fish/', priority: 'P2', pageType: 'creature-database', primaryKeyword: 'how to fish game all fish', secondaryKeywords: ['how to fish all fish locations', 'how to fish fish locations', 'how to fish rods and bait', 'how to fish lure list', 'how to fish fishipedia', 'how to fish collector achievement'],
    title: 'How to Fish Game: All Fish, Rods, Bait & Lures', description: 'Search every confirmed creature by lure, rod and area, track normal and Drip entries, and finish Collector and Fishipedia without guesswork.', h1: 'All Fish, Rods, Bait and Lures in How to Fish', eyebrow: 'CREATURE DATABASE · EVIDENCE FIRST',
    quickAnswer: 'Use the database to search confirmed and community-documented creatures by name, type, lure, rod, and first available area. It deliberately does not claim a total fish count or say a creature is found only on one island. A high-traffic Steam guide reports that lure can determine catch selection, so treat area as an observation, not an absolute spawn rule.',
    contentStatus: 'version-sensitive', spoilerLevel: 'minor', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fisher reeling in a colorful creature from a small boat',
    keyFacts: [{ label: 'Cross-checked rows', value: '44 catches + Seagull' }, { label: 'Location model', value: 'First documented stage' }, { label: 'Collection', value: 'Collector + Fishipedia' }, { label: 'Patch fix', value: 'Fishipedia 1.0.5' }],
    sections: [
      { id: 'selection', title: 'How catch selection works', paragraphs: ['Current community evidence suggests lure may be more important than the island for some catches. The database therefore separates first available area, observed areas, lure, and rod.'] },
      { id: 'rods', title: 'Rods', paragraphs: ['Match the current quest and shop prompts. Exact rod tables remain incomplete until each option is observed in the live build. Unknown values stay blank instead of being copied from another guide.'] },
      { id: 'bait', title: 'Bait and lures', paragraphs: ['A missing catch may mean the wrong lure, wrong rod, missing quest stage, or reel timing—not necessarily the wrong island. Version-sensitive quest bait is labelled in the record notes.'] },
      { id: 'not-biting', title: 'Fish not biting troubleshooting', steps: ['Confirm that the active area expects reeling rather than the opening-area behavior.', 'Check the equipped rod and lure.', 'Read the current quest prompt for a required bait.', 'Move away and retry after clearing an active encounter.', 'If inventory changed after loading, stop and open the fixes page.'] },
      { id: 'unknown', title: 'Unknown and unverified entries', paragraphs: ['The MVP publishes a useful evidence-labelled subset. It does not pretend to be a complete count until the in-game Fishipedia is checked entry by entry.'] },
    ],
    faqs: [{ question: 'How many fish are in How to Fish?', answer: 'This guide does not publish a number until the current in-game collection can be verified.' }, { question: 'Are fish locked to one island?', answer: 'Not always according to current community evidence; use lure, rod, first-available area, and observed areas instead of an absolute location.' }],
    relatedPages: ['/achievements/#collector', '/achievements/fishipedia/', '/tips/', '/islands/', '/fixes/'], sources: ['steamStore', 'steamAchievements', 'patch105', 'allThingsFish', 'g2aFishList', 'bitingDiscussion'],
  }),
  page({
    route: '/tips/', priority: 'P2', pageType: 'mechanics-guide', primaryKeyword: 'how to fish game tips', secondaryKeywords: ['how to fish hidden mechanics', 'how to fish things the game does not tell you', 'how to fish game secrets', 'how to fish fish not biting', 'how to fish killscore', 'how to fish cooking'],
    title: 'How to Fish Game Tips: Hidden Mechanics Explained', description: 'Learn the systems the game barely explains: reeling after Island 1, Radar, lures, Killscore, cooking, quest drops, upgrades and progression traps.', h1: 'How to Fish Game Tips and Hidden Mechanics', eyebrow: 'THE GAME BARELY EXPLAINS',
    quickAnswer: 'When progression feels broken, first check the mechanic that changed: later fishing may require active reeling, catch selection can depend on lure and rod, Radar markers do not replace quest hand-ins, and valuable quest drops should not be sold early. Treat Killscore, cooking, Drip, and trick-shot advice as version-sensitive until reproduced.',
    contentStatus: 'version-sensitive', spoilerLevel: 'minor', image: '/assets/how-to-fish/guide-fishing-v2.webp', imageAlt: 'AI-generated cartoon fishing expedition on a vivid tropical ocean',
    keyFacts: [{ label: 'Best use', value: 'Mechanic blockers' }, { label: 'Fishing change', value: 'Check reel timing' }, { label: 'Collection', value: 'Normal + Drip' }, { label: 'Risk', value: 'Do not sell quest items' }],
    sections: [
      { id: 'fishing', title: 'Fishing changes after the first area', paragraphs: ['A frequent player question is that fish stop biting after the opening area. Before assuming a bug, test active reel timing and confirm the equipped lure and rod.'] },
      { id: 'radar', title: 'How the Radar works', paragraphs: ['Use markers to navigate toward the active objective. A marker does not mean an NPC hand-in, boss trigger, or item requirement is already satisfied.'] },
      { id: 'lure-rod-area', title: 'Lure vs rod vs area', paragraphs: ['Treat these as separate dimensions. “First available area” is not the same as “only spawn area,” and an observed catch does not prove exclusivity.'] },
      { id: 'systems', title: 'Killscore, cooking, and Drip', bullets: ['Killscore rewards how the kill is completed.', 'The grill and burnt-creature achievement confirm cooking matters.', 'Drip creatures feed the Fishipedia achievement.', 'Trick shots and gambling are optional payout/risk systems, not progression guarantees.'] },
      { id: 'traps', title: 'Common progression traps', bullets: ['Selling a quest-marked result.', 'Following an outdated island skip after Patch 1.0.5.', 'Using a copied absolute fish location.', 'Assuming default-difficulty timing on Easy or Hard.', 'Testing save recovery on the only copy.'] },
    ],
    faqs: [{ question: 'Why are fish not biting after the first area?', answer: 'Check active reeling, the equipped lure and rod, and the current quest bait before treating it as a bug.' }, { question: 'Should I sell every valuable creature?', answer: 'No. Keep quest-marked creatures and boss results until the related hand-in and route unlock are complete.' }],
    relatedPages: ['/fish/', '/walkthrough/', '/islands/', '/achievements/', '/fixes/'], sources: ['steamStore', 'steamAchievements', 'tipsVideo', 'bitingDiscussion', 'communityGuide'],
  }),
  page({
    route: '/multiplayer/', priority: 'P1', pageType: 'multiplayer-guide', primaryKeyword: 'how to fish multiplayer', secondaryKeywords: ['how to fish co op', 'how many players is how to fish', 'how to fish invite friends', 'how to fish lobby id', 'how to fish steam relay', 'how to fish black screen joining'],
    title: 'How to Fish Multiplayer: 1–4 vs 8 Players & Lobbies', description: 'Understand the 1–4 design and eight-slot support, host public or private rooms, invite friends, find teammates, and diagnose joins.', h1: 'How to Play How to Fish Multiplayer', eyebrow: 'P1 CO-OP · LOBBIES & TEAMMATES',
    quickAnswer: 'How to Fish is intended for 1–4 players and sold that way. Patch 1.0.4 added lobby support up to eight, while Patch 1.0.5 added private invite-only sessions and in-game session-type changes that require a restart. Match patches, choose the room visibility intentionally, test a small group first, and check Steam Relay when joins fail.',
    contentStatus: 'still-reported', spoilerLevel: 'none', image: '/assets/how-to-fish/steam-quest.jpg', imageAlt: 'Official How to Fish screenshot showing players together during a quest',
    keyFacts: [{ label: 'Intended', value: '1–4 players' }, { label: 'Lobby support', value: 'Up to 8 since 1.0.4' }, { label: 'Network check', value: 'Steam Relay indicator' }, { label: 'Solo', value: 'Supported' }],
    sections: [
      { id: 'players', title: 'How many players does How to Fish support?', paragraphs: ['The store describes a 1–4 player physics-based fishing simulator. Patch 1.0.4 added support for up to eight-player lobbies. Describe the distinction instead of calling it a native eight-player design.'] },
      { id: 'visibility', title: 'Should you host public, private, or invite-only?', paragraphs: ['Patch 1.0.5 officially added a private lobby that is joinable only through an invite and allows session type changes in server settings after a restart. Player reports also show open and invite-only choices in the host flow. Use private or invite-only for a known group; use open only when you accept unknown joiners.'] },
      { id: 'invite', title: 'How should friends join the same room?', steps: ['Update Steam and How to Fish for every participant.', 'Enable the Steam Overlay if you use the in-game friend finder.', 'Create the intended session type and restart after changing it.', 'Invite from the in-game or current Steam lobby controls.', 'Test one joiner before sharing a lobby ID or adding the full group.'] },
      { id: 'larger-room', title: 'How should a five-to-eight-player room be tested?', paragraphs: ['Build a stable 1–4 room first, then add players five through eight one at a time. Steam forum reports show later slots can fail even though Patch 1.0.4 added support. Record the exact slot, host, and Relay state instead of assuming an eight-slot room has the same reliability as the intended core group.'] },
      { id: 'teammates', title: 'Where can solo players find teammates?', paragraphs: ['The official Dazed Games Steam forum and developer-linked Discord both contain active looking-for-group posts. Share region, language, microphone preference, fresh-save or current-island state, desired room size, and whether the lobby is public or invite-only. Never publish another player’s private contact details.'] },
      { id: 'relay', title: 'What should you check when joining fails?', steps: ['Check the Relay text added in Patch 1.0.9.', 'If it is red, follow current developer-linked common-bugs guidance.', 'Restart Steam and confirm matching patch versions.', 'Retry a fresh private lobby with one host and one joiner.', 'Use the black-screen page if solo works but the join stays black.'] },
    ],
    evidenceRows: [
      { topic: 'Player count', official: 'Steam sells How to Fish as 1–4 players; Patch 1.0.4 adds up to eight lobby support.', community: 'Reports show some larger-room joins failing above four.', guidance: 'Describe design and technical slots separately.' },
      { topic: 'Session privacy', official: 'Patch 1.0.5 added private invite-only hosting and session-type changes after restart.', community: 'Players report private, invite-only, and open options in the host flow.', guidance: 'Use the live host UI and restart after a change.' },
      { topic: 'Finding players', official: 'Patch 1.0.9 points players to the developer Discord for other players and tips.', community: 'The Steam forum carries active looking-for-group posts.', guidance: 'Share only necessary session details and protect private contact data.' },
    ],
    failureBranches: [
      { symptom: 'Invite button does nothing', likelyState: 'Steam Overlay or Steam connection path is unavailable', nextStep: 'Enable Overlay, inspect Relay, restart Steam, and test the in-game invite again.' },
      { symptom: 'Session type did not change', likelyState: 'Patch 1.0.5 requires a restart after changing server settings', nextStep: 'Restart the session, then confirm the live visibility state.' },
      { symptom: 'Players 1–4 work but later joins fail', likelyState: 'Extended-lobby threshold issue', nextStep: 'Keep the smaller working room and add later slots individually.' },
      { symptom: 'Joiner sees a black screen', likelyState: 'Join-only client, host, or Relay failure', nextStep: 'Use the canonical black-screen diagnostic at /fixes/black-screen/.' },
    ],
    faqs: [{ question: 'Is How to Fish an eight-player game?', answer: 'It is intended for 1–4 players; Patch 1.0.4 added technical lobby support for up to eight.' }, { question: 'What does a red Steam Relay status mean?', answer: 'Patch 1.0.9 directs players to the official Discord common-bugs guidance when Relay initialization fails.' }],
    relatedPages: ['/fixes/black-screen/', '/bosses/', '/fixes/', '/walkthrough/', '/achievements/'], sources: ['steamStore', 'patch104', 'patch105', 'patch109', 'patch110', 'lobbySetupDiscussion', 'eightPlayerDiscussion', 'blackScreenDiscussion'],
  }),
  page({
    route: '/platforms/', priority: 'P1', pageType: 'platform-status', primaryKeyword: 'how to fish game platforms', secondaryKeywords: ['how to fish xbox', 'how to fish ps5', 'how to fish mac', 'how to fish mobile', 'how to fish console release'],
    title: 'How to Fish Platforms: PC, Xbox, PS5, Mac & Mobile', description: 'Current official platform status for How to Fish: Windows PC release, undated console and Mac statement, and no mobile announcement.', h1: 'How to Fish Platform Availability', eyebrow: 'P1 STATUS · OFFICIAL ONLY',
    quickAnswer: 'How to Fish is currently released on Steam for Windows 10+ PCs. Dazed Games says console and Mac versions are coming but gives no date and does not name Xbox or PlayStation individually. The official pages checked do not announce iOS or Android. Treat storefront listings—not requests, controller glyphs, or old pitch decks—as the current availability test.',
    contentStatus: 'version-sensitive', spoilerLevel: 'none', image: '/assets/how-to-fish/steam-shop.jpg', imageAlt: 'Official How to Fish screenshot showing the in-game shop and Windows PC interface', keyFacts: [{ label: 'Available now', value: 'Windows PC via Steam' }, { label: 'Console', value: 'Confirmed generally; no date' }, { label: 'Mac', value: 'Confirmed generally; no date' }, { label: 'Mobile', value: 'No official announcement found' }],
    sections: [
      { id: 'pc', title: 'Where can you play How to Fish now?', paragraphs: ['The live Steam store lists a Windows 10+ minimum operating system, and the current app configuration exposes a Windows executable. This is the only released platform state confirmed by the sources checked on August 29, 2026.'] },
      { id: 'xbox-ps5', title: 'Is How to Fish on Xbox or PS5?', paragraphs: ['No current Xbox or PlayStation storefront release was confirmed. Dazed Games says “consoles” are coming but does not name Xbox, PS5, a console generation, or a date. PlayStation controller glyphs added in Patch 1.0.8 are input UI support, not evidence of a PS5 release.'] },
      { id: 'mac', title: 'Is there a Mac version?', paragraphs: ['The developer FAQ includes Mac in its general future statement but says it does not know when. The current Steam listing provides Windows requirements and no released macOS build. This page records both facts without predicting timing.'] },
      { id: 'mobile', title: 'Is How to Fish on iPhone or Android?', paragraphs: ['No iOS or Android release, store listing, or mobile plan was found in the current official Steam store or Dazed Games FAQ. Search results for similarly named fishing games are not How to Fish by Dazed Games.'] },
      { id: 'verify', title: 'How should you verify a new platform release?', steps: ['Check the Dazed Games website and official Steam announcements.', 'Look for a platform-holder storefront page naming Dazed Games.', 'Match the exact title, developer, and Steam App 4001890 identity.', 'Do not treat a forum request, controller icon, or similarly named game as release confirmation.'] },
    ],
    evidenceRows: [
      { topic: 'Windows PC', official: 'Steam lists Windows 10+ and the released PC game.', community: 'SteamDB mirrors a Windows executable.', guidance: 'Available now is confirmed.' },
      { topic: 'Console and Mac', official: 'Dazed Games says consoles and Mac are coming but gives no date.', community: 'Players request Xbox and PlayStation versions.', guidance: 'Do not turn requests into named-platform confirmation or a schedule.' },
      { topic: 'Mobile', official: 'No official mobile announcement was found.', community: 'Similar game names can appear in mobile or console search.', guidance: 'Match exact developer and title before claiming availability.' },
    ],
    failureBranches: [
      { symptom: 'An Xbox or PlayStation search shows a similar title', likelyState: 'Different fishing game or unverified listing', nextStep: 'Check the developer is Dazed Games and look for an official cross-link.' },
      { symptom: 'Steam shows controller glyphs', likelyState: 'PC input support rather than a console release', nextStep: 'Use storefront availability as the release test.' },
      { symptom: 'An old pitch deck lists PC/Mac', likelyState: 'Pre-release target, not current storefront state', nextStep: 'Prefer the current Steam listing and developer FAQ.' },
      { symptom: 'A port request appears in a forum', likelyState: 'Player demand only', nextStep: 'Wait for a Dazed Games announcement or official platform storefront.' },
    ],
    faqs: [{ question: 'Can I buy How to Fish on Xbox or PS5 now?', answer: 'No official Xbox or PlayStation release was confirmed. The developer only gives a general undated console statement.' }, { question: 'Does the developer plan a Mac version?', answer: 'Dazed Games says yes, but provides no date; the current Steam release is Windows.' }, { question: 'Is there a mobile version?', answer: 'No official iOS or Android release or announcement was found in the checked sources.' }],
    relatedPages: ['/multiplayer/', '/fixes/', '/', '/about/'], sources: ['steamStore', 'dazedGamesFaq', 'steamDbConfig', 'patch110'],
  }),
  page({
    route: '/gambling/', priority: 'P1', pageType: 'mechanics-guide', primaryKeyword: 'how to fish game gambling', secondaryKeywords: ['how to fish roulette', 'how to fish all in achievement', 'how to fish gold gold gold', 'how to fish drip gambling'],
    title: 'How to Fish Gambling Guide: Roulette, Drip & GOLD', description: 'One canonical guide for Roulette, All in, Reel of Fortune, Drip catches, GOLD GOLD GOLD, and the no-real-money boundary.', h1: 'How to Fish Gambling and Roulette', eyebrow: 'P1 CANONICAL · OPTIONAL RISK',
    quickAnswer: 'How to Fish gambling uses fish and in-game value, never real money. Roulette’s All in achievement requires betting on green and winning; Reel of Fortune uses Drip catches for a random skin outcome, including the legendary result tied to GOLD GOLD GOLD. Keep quest trophies and the value needed for your next progression purchase outside every gamble.',
    contentStatus: 'version-sensitive', spoilerLevel: 'none', image: '/assets/how-to-fish/steam-shop.jpg', imageAlt: 'Official How to Fish screenshot showing an in-game shop and optional economy systems', keyFacts: [{ label: 'Real money', value: 'None' }, { label: 'Roulette', value: 'All in: green win' }, { label: 'Reel of Fortune', value: 'Uses Drip catches' }, { label: 'Legendary skin', value: 'Random outcome' }],
    sections: [
      { id: 'boundary', title: 'What does the game officially call gambling?', paragraphs: ['The Steam store says the game includes gambling with fish and explicitly says no real money is involved. Treat it as an optional in-game risk system, not a purchase, deposit, or progression requirement.'] },
      { id: 'roulette', title: 'How does Roulette connect to All in?', paragraphs: ['Steam defines All in as betting on green and winning at Roulette. The description establishes the target but not a guaranteed sequence, probability, or bankroll. Decide the maximum replaceable value before placing the bet and stop when that limit is reached.'] },
      { id: 'drip', title: 'How does Drip connect to Reel of Fortune?', paragraphs: ['Steam defines Drip as a rare creature variant and GOLD GOLD GOLD as unlocking a legendary skin from the slot machine. Community routes use Drip catches at Reel of Fortune. The skin outcome is random, so no number of attempts is promised.'] },
      { id: 'protect', title: 'What should never enter a gamble?', bullets: ['A boss trophy or quest-marked result.', 'The only catch needed for an active NPC hand-in.', 'The value reserved for the next required rod, lure, weapon, healing, or boat upgrade.', 'An item whose loss would force a save-recovery experiment.'] },
      { id: 'patch', title: 'What changed in Patch 1.0.10?', paragraphs: ['Patch 1.0.10 fixed infinite Roulette ticking at high values, attempted to stop the ball clipping through the wheel, and fixed a session-breaking state after leaving during Roulette. The “hopefully” wording on ball clipping remains an attempted fix, not a guarantee.'] },
    ],
    evidenceRows: [
      { topic: 'Boundary', official: 'The store says gambling uses fish and no real money.', community: 'Players optimize catches and skins around the machines.', guidance: 'Keep the guide strictly inside in-game items and value.' },
      { topic: 'Achievements', official: 'All in requires a green Roulette win; GOLD GOLD GOLD requires a legendary slot-machine skin.', community: 'Drip farming and bankroll routes are player strategies.', guidance: 'State the official condition and label strategies as optional.' },
      { topic: 'Patch status', official: 'Patch 1.0.10 fixed several Roulette session bugs and cautiously addressed clipping.', community: 'Players may still report inconsistent results.', guidance: 'Do not interpret a failed spin as an achievement bug without the correct outcome.' },
    ],
    failureBranches: [
      { symptom: 'A green bet loses', likelyState: 'Normal Roulette outcome rather than a failed achievement', nextStep: 'Stop at the preselected risk limit; no win is guaranteed.' },
      { symptom: 'No legendary skin appears', likelyState: 'Random slot-machine outcome', nextStep: 'Use only replaceable Drip catches and avoid a promised attempt count.' },
      { symptom: 'Roulette keeps ticking or breaks after leaving', likelyState: 'Session behavior addressed in Patch 1.0.10', nextStep: 'Confirm the current patch, restart the session, and report if it repeats.' },
      { symptom: 'A quest trophy is selected', likelyState: 'Progression item is at risk', nextStep: 'Cancel the gamble and complete the hand-in first.' },
    ],
    faqs: [{ question: 'Does How to Fish use real-money gambling?', answer: 'No. The developer says the game gambles with fish and includes no real money.' }, { question: 'What unlocks All in?', answer: 'Steam requires betting on green and winning at Roulette.' }, { question: 'Is GOLD GOLD GOLD guaranteed after a fixed number of Drip catches?', answer: 'No fixed attempt count is published; the legendary skin outcome is random.' }],
    relatedPages: ['/tips/', '/achievements/', '/fish/', '/walkthrough/'], sources: ['steamStore', 'steamAchievements', 'patch110', 'communityGuide'],
  }),
  page({
    route: '/fixes/', priority: 'P1', pageType: 'troubleshooting-hub', primaryKeyword: 'how to fish save bug', secondaryKeywords: ['how to fish lost items', 'how to fish missing radar', 'how to fish corrupted save', 'how to fish game name save', 'how to fish black screen', 'how to fish game crash'],
    title: 'How to Fish Save Bug & Fixes: Lost Items and Black Screen', description: 'Protect saves and troubleshoot corrupted slots, lost items, missing Radar, startup black screens, crashes, audio problems and stuttering by patch status.', h1: 'How to Fix How to Fish Save and Launch Problems', eyebrow: 'PATCH STATUS · SAFE FIRST STEPS',
    quickAnswer: 'Patch 1.0.10 now saves up to 64 dropped items with priority for important objects and includes another cautiously worded attempted fix for loading behavior, but it does not guarantee recovery. Protect the affected save, classify the exact symptom, restart Steam, verify files, and use the dedicated black-screen or audio draft only when that branch matches what you actually see.',
    contentStatus: 'attempted-fix', spoilerLevel: 'none', image: '/assets/how-to-fish/steam-gear.jpg', imageAlt: 'Official How to Fish screenshot showing weapons and tools that can be affected by save or cooking issues',
    keyFacts: [{ label: 'Current baseline', value: 'Patch 1.0.10' }, { label: 'Recovery', value: 'Not guaranteed' }, { label: 'First action', value: 'Protect the save copy' }, { label: 'Network', value: 'Check Steam Relay' }],
    sections: [
      { id: 'before', title: 'Before trying any fix', steps: ['Do not overwrite the only save.', 'Back up the save using current official guidance.', 'Restart Steam and the computer.', 'Confirm that Patch 1.0.9 or newer is installed.', 'Verify the game files in Steam.'] },
      { id: 'saves', title: 'Save corruption, lost items, and Missing Radar', paragraphs: ['Community reports include lost inventory, upgrades, boat items, and Radar after loading. These reports establish the problem, not a universal cause. Patch 1.0.9 says “Hopefully fixed save files being corrupted” and directs remaining cases to the official Discord.'] },
      { id: 'launch', title: 'Black screens, crashes, and weapon problems', bullets: ['For a join-only black screen, use the Multiplayer page and Relay check.', 'For startup display issues, verify files and current display settings before editing saves.', 'For crashes while equipping weapons, use the official Discord path cited in Patch 1.0.9.', 'Avoid deleting files based on an old community post.'] },
      { id: 'status', title: 'Official fix vs community workaround', paragraphs: ['Official Fix means the patch note states a fix. Attempted Fix preserves cautious wording such as “Hopefully.” Community Workaround means players reported a step, not that the developer verified it. Still Reported means current reports remain after a patch.'] },
      { id: 'performance', title: 'Audio and stuttering', steps: ['Restart the game and close unnecessary overlays.', 'Verify files and update the graphics driver through its official tool.', 'Test lower graphics and a stable frame cap.', 'Record the exact area, action, and patch before reporting.'] },
      { id: 'merged-intents', title: 'Which broad problem terms stay on this hub?', bullets: ['How to Fish game: fish not biting (in-game) — check active reeling, rod, lure, and quest bait; this is intentionally not a standalone page.', 'Cooked weapon — Patch 1.0.10 says weapons and tools can be cleaned by dipping them in water; inspect the item afterward.', 'FPS drops / high GPU — test a stable frame cap, lower graphics, close overlays, and record the exact scene; no standalone page is published.', 'Audio glitch — use the noindex evidence draft for reversible checks; there is no guaranteed fix.'] },
    ],
    faqs: [{ question: 'Did Patch 1.0.9 completely fix corrupted saves?', answer: 'No. The patch note describes an attempted fix and directs remaining loading or weapon-crash cases to official Discord guidance.' }, { question: 'Can this guide recover lost items?', answer: 'No recovery can be guaranteed. Protect the save copy and follow current official support instructions.' }],
    relatedPages: ['/fixes/black-screen/', '/fixes/audio-glitch/', '/multiplayer/', '/walkthrough/', '/tips/', '/islands/'], sources: ['patch110', 'patch109', 'patch104', 'saveDiscussion', 'blackScreenDiscussion', 'bitingDiscussion', 'audioDiscussion'],
  }),
];

export const seoPages: GuidePage[] = [...corePages, ...innerPages];

export function getPageByRoute(route: string): GuidePage {
  const normalized = route === '/' ? '/' : `${route.replace(/\/+$/, '')}/`;
  const result = seoPages.find((item) => item.route === normalized);
  if (!result) throw new Error(`Unknown guide route: ${route}`);
  return result;
}

export const searchEntries = seoPages.map((item) => ({
  title: item.h1,
  summary: item.description,
  href: item.route,
  category: item.eyebrow,
  keywords: [item.primaryKeyword, ...item.secondaryKeywords],
}));
