import type { SourceReference } from './types';
import { siteStatus } from './site-status';

const accessedAt = siteStatus.lastChecked;

export const sources: Record<string, SourceReference> = {
  steamStore: {
    id: 'steam-store',
    label: 'How to Fish on Steam',
    publisher: 'Dazed Games / Steam',
    url: 'https://store.steampowered.com/app/4001890/How_to_Fish/',
    sourceLevel: 'official',
    sourceType: 'steam-store',
    accessedAt,
    notes: 'Official identity, release date, 1–4 player positioning, feature list, gameplay loop, and developer links.',
  },
  steamAchievements: {
    id: 'steam-achievements',
    label: 'How to Fish global achievements',
    publisher: 'Steam Community',
    url: 'https://steamcommunity.com/stats/4001890/achievements/?l=english',
    sourceLevel: 'official',
    sourceType: 'steam-achievements',
    accessedAt,
    notes: 'Official names, descriptions, completion rates, and total of 28 achievements.',
  },
  patch109: {
    id: 'patch-1-0-9',
    label: 'Patch 1.0.9',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24911270/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Difficulty settings, Steam Relay diagnostic, and cautiously worded attempted save-corruption fix.',
  },
  patch104: {
    id: 'patch-1-0-4',
    label: 'Patch 1.0.4',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24866339/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Added support for up to eight-player lobbies and attempted a lobby black-screen fix.',
  },
  patch105: {
    id: 'patch-1-0-5',
    label: 'Patch 1.0.5',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24880906/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Closed the skip-any-island bug and corrected the Fishipedia unlock condition.',
  },
  saveDiscussion: {
    id: 'save-discussion',
    label: 'Saved game and lost everything?',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178592050/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player reports about lost inventory and save loading; reports are not proof of a universal cause or recovery method.',
  },
  blackScreenDiscussion: {
    id: 'join-black-screen',
    label: 'Black screen when joining friends',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178508963/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player reports used to identify the troubleshooting intent; Patch 1.0.4 and 1.0.9 remain the status authority.',
  },
  beanDiscussion: {
    id: 'bean-discussion',
    label: 'How to get Bean achievement now?',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606510389/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Current player discussion after the island-skip route was removed in Patch 1.0.5.',
  },
  communityGuide: {
    id: 'community-route-guide',
    label: 'All 28 Achievements and post-game route',
    publisher: 'Steam Community guide',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3788027308',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Route and lure observations used as leads; version-sensitive steps stay labelled until repeated in-game.',
  },
  destructoidWalkthrough: {
    id: 'destructoid-walkthrough',
    label: 'Complete How to Fish walkthrough',
    publisher: 'Destructoid',
    url: 'https://www.destructoid.com/complete-how-to-fish-game-walkthrough-100-completion/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'First-hand screenshots and route observations for all five areas; exact prices and loadouts remain author-specific.',
  },
  pcGamerSpiderCrab: {
    id: 'pc-gamer-spider-crab',
    label: 'Spider Crab strategy',
    publisher: 'PC Gamer',
    url: 'https://www.pcgamer.com/games/sim/how-to-fish-spider-crab/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'First-hand solo and co-op observations for the opening boss, terrain use, and missed-charge damage window.',
  },
  pcGamerPufferfish: {
    id: 'pc-gamer-pufferfish',
    label: 'Pufferfish strategy',
    publisher: 'PC Gamer',
    url: 'https://www.pcgamer.com/games/sim/how-to-fish-pufferfish/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'First-hand route and fight observations; supports movement and upgraded SMG guidance without establishing a universal loadout.',
  },
  allThingsFish: {
    id: 'all-things-fish-list',
    label: 'All fish locations and bait',
    publisher: 'AllThings.How',
    url: 'https://allthings.how/how-to-fish-all-fish-locations-and-the-bait-you-need/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Cross-check for 34 regular catches, 10 bosses or mini-bosses, lure tiers, and quest bait relationships.',
  },
  g2aFishList: {
    id: 'g2a-fish-list',
    label: 'All fish, bosses, rods and bait',
    publisher: 'G2A News',
    url: 'https://www.g2a.com/news/features/guide/how-to-fish-all-fish-bosses-rods-and-bait-by-island/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Independent cross-check for the same 44 catch and boss records; not proof of exclusive spawn areas.',
  },
  leechDiscussion: {
    id: 'leeches-not-spawning',
    label: 'Leeches not spawning',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178562048/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Conflicting player reports about dialogue, searching, and reloading; used only for a cautious diagnostic order.',
  },
  radarDiscussion: {
    id: 'lost-radar-island-2',
    label: 'Lost Radar on Island 2',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606725684/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Multiple players report a replacement Radar on later-island shop boards; exact availability remains community-sourced.',
  },
  inventorySaveDiscussion: {
    id: 'inventory-save-developer-reply',
    label: 'Items missing after loading',
    publisher: 'Steam Community discussion with developer reply',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178605260/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Developer reply distinguishes inventory from items left on the ground and acknowledges the inconvenience.',
  },
  error011c7Discussion: {
    id: 'error-0x11c7-discussion',
    label: 'Smart App Control error 0x11C7',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606626325/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player report identifies a Windows Code Integrity application-control block; reinstalling helped one reply but is not a guaranteed fix.',
  },
  microsoftSmartAppControl: {
    id: 'microsoft-smart-app-control',
    label: 'Smart App Control guidance',
    publisher: 'Microsoft Support',
    url: 'https://support.microsoft.com/en-us/windows/security/windows-security/app-browser-control-in-the-windows-security-app',
    sourceLevel: 'official',
    sourceType: 'platform-support',
    accessedAt,
    notes: 'Official Windows guidance for Smart App Control modes, updates, security role, and version-dependent setting behavior.',
  },
  islandsGuide: {
    id: 'islands-guide',
    label: 'All islands and unlock route',
    publisher: 'Destructoid',
    url: 'https://www.destructoid.com/all-islands-coordinates-locations-how-to-fish/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Third-party route reference used to reconcile the Lighthouse plus four unlockable areas counting convention.',
  },
  tipsVideo: {
    id: 'tips-video',
    label: "10 Things the Game Doesn't Tell You",
    publisher: 'YouTube gameplay guide',
    url: 'https://www.youtube.com/watch?v=Mi94jv9ttWc',
    sourceLevel: 'community',
    sourceType: 'youtube',
    accessedAt,
    notes: 'Gameplay footage used to identify unclear systems; individual claims remain version-sensitive.',
  },
  bitingDiscussion: {
    id: 'fish-not-biting',
    label: 'Fish not biting discussion',
    publisher: 'How to Fish community on Reddit',
    url: 'https://www.reddit.com/r/HowToFish/comments/1vvglei/fish_not_biting/',
    sourceLevel: 'community',
    sourceType: 'reddit',
    accessedAt,
    notes: 'Player question used to define the reel/rod/lure troubleshooting checklist.',
  },
  steamMedia: {
    id: 'steam-media',
    label: 'Official How to Fish screenshots',
    publisher: 'Dazed Games / Steam',
    url: 'https://store.steampowered.com/app/4001890/How_to_Fish/',
    sourceLevel: 'official',
    sourceType: 'steam-store',
    accessedAt,
    notes: 'Official promotional screenshots used for visual context, not as proof of exact route steps or values.',
  },
};

export function resolveSources(ids: string[]) {
  return ids.map((id) => sources[id]).filter(Boolean);
}
