import type { SourceReference } from './types';

const accessedAt = '2026-08-25';

export const sources: Record<string, SourceReference> = {
  steamStore: {
    id: 'steam-store',
    label: 'How to Fish on Steam',
    publisher: 'Dazed Games / Steam',
    url: 'https://store.steampowered.com/app/4001890/How_to_Fish/',
    sourceLevel: 'official',
    sourceType: 'steam-store',
    accessedAt,
    notes: 'Official identity, release date, 1–4 player positioning, feature list, gameplay loop, and developer links.',
  },
  steamAchievements: {
    id: 'steam-achievements',
    label: 'How to Fish global achievements',
    publisher: 'Steam Community',
    url: 'https://steamcommunity.com/stats/4001890/achievements/?l=english',
    sourceLevel: 'official',
    sourceType: 'steam-achievements',
    accessedAt,
    notes: 'Official names, descriptions, completion rates, and total of 28 achievements.',
  },
  patch109: {
    id: 'patch-1-0-9',
    label: 'Patch 1.0.9',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24911270/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Difficulty settings, Steam Relay diagnostic, and cautiously worded attempted save-corruption fix.',
  },
  patch104: {
    id: 'patch-1-0-4',
    label: 'Patch 1.0.4',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24866339/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Added support for up to eight-player lobbies and attempted a lobby black-screen fix.',
  },
  patch105: {
    id: 'patch-1-0-5',
    label: 'Patch 1.0.5',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24880906/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Closed the skip-any-island bug and corrected the Fishipedia unlock condition.',
  },
  saveDiscussion: {
    id: 'save-discussion',
    label: 'Saved game and lost everything?',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178592050/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player reports about lost inventory and save loading; reports are not proof of a universal cause or recovery method.',
  },
  blackScreenDiscussion: {
    id: 'join-black-screen',
    label: 'Black screen when joining friends',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178508963/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player reports used to identify the troubleshooting intent; Patch 1.0.4 and 1.0.9 remain the status authority.',
  },
  beanDiscussion: {
    id: 'bean-discussion',
    label: 'How to get Bean achievement now?',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606510389/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Current player discussion after the island-skip route was removed in Patch 1.0.5.',
  },
  communityGuide: {
    id: 'community-route-guide',
    label: 'All 28 Achievements and post-game route',
    publisher: 'Steam Community guide',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3788027308',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Route and lure observations used as leads; version-sensitive steps stay labelled until repeated in-game.',
  },
  islandsGuide: {
    id: 'islands-guide',
    label: 'All islands and unlock route',
    publisher: 'Destructoid',
    url: 'https://www.destructoid.com/all-islands-coordinates-locations-how-to-fish/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Third-party route reference used to reconcile the Lighthouse plus four unlockable areas counting convention.',
  },
  tipsVideo: {
    id: 'tips-video',
    label: "10 Things the Game Doesn't Tell You",
    publisher: 'YouTube gameplay guide',
    url: 'https://www.youtube.com/watch?v=Mi94jv9ttWc',
    sourceLevel: 'community',
    sourceType: 'youtube',
    accessedAt,
    notes: 'Gameplay footage used to identify unclear systems; individual claims remain version-sensitive.',
  },
  bitingDiscussion: {
    id: 'fish-not-biting',
    label: 'Fish not biting discussion',
    publisher: 'How to Fish community on Reddit',
    url: 'https://www.reddit.com/r/HowToFish/comments/1vvglei/fish_not_biting/',
    sourceLevel: 'community',
    sourceType: 'reddit',
    accessedAt,
    notes: 'Player question used to define the reel/rod/lure troubleshooting checklist.',
  },
  steamMedia: {
    id: 'steam-media',
    label: 'Official How to Fish screenshots',
    publisher: 'Dazed Games / Steam',
    url: 'https://store.steampowered.com/app/4001890/How_to_Fish/',
    sourceLevel: 'official',
    sourceType: 'steam-store',
    accessedAt,
    notes: 'Official promotional screenshots used for visual context, not as proof of exact route steps or values.',
  },
};

export function resolveSources(ids: string[]) {
  return ids.map((id) => sources[id]).filter(Boolean);
}
