import type { SourceReference } from './types';
import { siteStatus } from './site-status';

const accessedAt = siteStatus.lastChecked;

export const sources: Record<string, SourceReference> = {
  steamStore: {
    id: 'steam-store',
    label: 'How to Fish on Steam',
    publisher: 'Dazed Games / Steam',
    url: 'https://store.steampowered.com/app/4001890/How_to_Fish/',
    sourceLevel: 'official',
    sourceType: 'steam-store',
    accessedAt,
    notes: 'Official identity, release date, 1–4 player positioning, feature list, gameplay loop, and developer links.',
  },
  steamAchievements: {
    id: 'steam-achievements',
    label: 'How to Fish global achievements',
    publisher: 'Steam Community',
    url: 'https://steamcommunity.com/stats/4001890/achievements/?l=english',
    sourceLevel: 'official',
    sourceType: 'steam-achievements',
    accessedAt,
    notes: 'Official names, descriptions, completion rates, and total of 28 achievements.',
  },
  patch109: {
    id: 'patch-1-0-9',
    label: 'Patch 1.0.9',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24911270/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Difficulty settings, Steam Relay diagnostic, and cautiously worded attempted save-corruption fix.',
  },
  patch110: {
    id: 'patch-1-0-10',
    label: 'Fanart & Patch 1.0.10',
    publisher: 'Dazed Games / Steam Community',
    url: 'https://steamcommunity.com/app/4001890/announcements/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Current official baseline: dropped-item persistence, cooked tool cleaning in water, connection timeout changes, and cautiously worded item-loading fixes.',
  },
  patch104: {
    id: 'patch-1-0-4',
    label: 'Patch 1.0.4',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24866339/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Added support for up to eight-player lobbies and attempted a lobby black-screen fix.',
  },
  patch105: {
    id: 'patch-1-0-5',
    label: 'Patch 1.0.5',
    publisher: 'Dazed Games patch notes mirrored by SteamDB',
    url: 'https://steamdb.info/patchnotes/24880906/',
    sourceLevel: 'official',
    sourceType: 'steam-patch',
    accessedAt,
    notes: 'Closed the skip-any-island bug and corrected the Fishipedia unlock condition.',
  },
  saveDiscussion: {
    id: 'save-discussion',
    label: 'Saved game and lost everything?',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178592050/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player reports about lost inventory and save loading; reports are not proof of a universal cause or recovery method.',
  },
  blackScreenDiscussion: {
    id: 'join-black-screen',
    label: 'Black screen when joining friends',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178508963/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player reports used to identify the troubleshooting intent; Patch 1.0.4 and 1.0.9 remain the status authority.',
  },
  lobbySetupDiscussion: {
    id: 'lobby-setup-discussion',
    label: 'Invite, lobby ID, and session visibility report',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606628056/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player-reported private, invite-only, and open session choices plus Steam Overlay failure symptoms; not official UI documentation.',
  },
  eightPlayerDiscussion: {
    id: 'eight-player-discussion',
    label: 'Up to eight players discussion',
    publisher: 'Steam Community discussion with developer replies',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/573793348713727408/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Reports distinguish the shipped four-player experience from later eight-slot support and show that larger-room joins were still inconsistent.',
  },
  beanDiscussion: {
    id: 'bean-discussion',
    label: 'How to get Bean achievement now?',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606510389/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Current player discussion after the island-skip route was removed in Patch 1.0.5.',
  },
  beanSoloGuide: {
    id: 'bean-1-0-5-solo-guide',
    label: 'Bean 1.0.5 Guide (Solo)',
    publisher: 'Steam Community guide by loomy',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3788641141',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Post-1.0.5 legitimate route with island-by-island budgets and a reported 54-minute completion; community evidence, not a guarantee.',
  },
  communityGuide: {
    id: 'community-route-guide',
    label: 'All 28 Achievements and post-game route',
    publisher: 'Steam Community guide',
    url: 'https://steamcommunity.com/sharedfiles/filedetails/?id=3788027308',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Route and lure observations used as leads; version-sensitive steps stay labelled until repeated in-game.',
  },
  destructoidWalkthrough: {
    id: 'destructoid-walkthrough',
    label: 'Complete How to Fish walkthrough',
    publisher: 'Destructoid',
    url: 'https://www.destructoid.com/complete-how-to-fish-game-walkthrough-100-completion/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'First-hand screenshots and route observations for all five areas; exact prices and loadouts remain author-specific.',
  },
  pcGamerSpiderCrab: {
    id: 'pc-gamer-spider-crab',
    label: 'Spider Crab strategy',
    publisher: 'PC Gamer',
    url: 'https://www.pcgamer.com/games/sim/how-to-fish-spider-crab/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'First-hand solo and co-op observations for the opening boss, terrain use, and missed-charge damage window.',
  },
  pcGamerPufferfish: {
    id: 'pc-gamer-pufferfish',
    label: 'Pufferfish strategy',
    publisher: 'PC Gamer',
    url: 'https://www.pcgamer.com/games/sim/how-to-fish-pufferfish/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'First-hand route and fight observations; supports movement and upgraded SMG guidance without establishing a universal loadout.',
  },
  pufferfishVideo: {
    id: 'pufferfish-video',
    label: 'Pufferfish gameplay route',
    publisher: 'YouTube gameplay guide',
    url: 'https://www.youtube.com/watch?v=M2isiOmxH7w',
    sourceLevel: 'community',
    sourceType: 'youtube',
    accessedAt,
    notes: 'Current gameplay reference for the trigger and fight flow; poison timing is treated as a visual exit cue, not a fixed number.',
  },
  finalBossVideo: {
    id: 'final-boss-route-video',
    label: 'Full-game speed route with final encounter',
    publisher: 'YouTube gameplay guide',
    url: 'https://www.youtube.com/watch?v=615yz4UD1nM',
    sourceLevel: 'community',
    sourceType: 'youtube',
    accessedAt,
    notes: 'Full route footage used only as a visual reference for late-game sequencing; exact timing and loadout remain player-specific.',
  },
  finalBossGuide: {
    id: 'mutated-whale-final-boss-guide',
    label: 'Mutated Bowhead Whale final boss route',
    publisher: 'AllThings.How',
    url: 'https://allthings.how/how-to-fish-how-to-beat-the-mutated-bowhead-whale-lava-whale-final-boss/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Attributed current route for the Bowhead Whale, Volcano trigger, fight branches, trophy hand-in, and RHIB ending.',
  },
  boatFlyGuide: {
    id: 'boat-fly-guide',
    label: "How to make the boat fly",
    publisher: 'Destructoid',
    url: 'https://www.destructoid.com/how-to-make-your-boat-fly-in-how-to-fish-im-the-bird-now-achievement/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'First-hand dynamite launch route and post-launch recovery report; official achievement text remains the requirement authority.',
  },
  boatFlyVideo: {
    id: 'boat-fly-video',
    label: "I'm the bird now gameplay clip",
    publisher: 'YouTube gameplay guide',
    url: 'https://www.youtube.com/watch?v=nnFQFXgFxZI',
    sourceLevel: 'community',
    sourceType: 'youtube',
    accessedAt,
    notes: 'Visual example of a community boat-launch method; not proof that one placement is guaranteed on every patch.',
  },
  allThingsFish: {
    id: 'all-things-fish-list',
    label: 'All fish locations and bait',
    publisher: 'AllThings.How',
    url: 'https://allthings.how/how-to-fish-all-fish-locations-and-the-bait-you-need/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Cross-check for 34 regular catches, 10 bosses or mini-bosses, lure tiers, and quest bait relationships.',
  },
  g2aFishList: {
    id: 'g2a-fish-list',
    label: 'All fish, bosses, rods and bait',
    publisher: 'G2A News',
    url: 'https://www.g2a.com/news/features/guide/how-to-fish-all-fish-bosses-rods-and-bait-by-island/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Independent cross-check for the same 44 catch and boss records; not proof of exclusive spawn areas.',
  },
  leechDiscussion: {
    id: 'leeches-not-spawning',
    label: 'Leeches not spawning',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178562048/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Conflicting player reports about dialogue, searching, and reloading; used only for a cautious diagnostic order.',
  },
  radarDiscussion: {
    id: 'lost-radar-island-2',
    label: 'Lost Radar on Island 2',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606725684/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Multiple players report a replacement Radar on later-island shop boards; exact availability remains community-sourced.',
  },
  inventorySaveDiscussion: {
    id: 'inventory-save-developer-reply',
    label: 'Items missing after loading',
    publisher: 'Steam Community discussion with developer reply',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582805931178605260/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Developer reply distinguishes inventory from items left on the ground and acknowledges the inconvenience.',
  },
  error011c7Discussion: {
    id: 'error-0x11c7-discussion',
    label: 'Smart App Control error 0x11C7',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/582806239606626325/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player report identifies a Windows Code Integrity application-control block; reinstalling helped one reply but is not a guaranteed fix.',
  },
  microsoftSmartAppControl: {
    id: 'microsoft-smart-app-control',
    label: 'Smart App Control guidance',
    publisher: 'Microsoft Support',
    url: 'https://support.microsoft.com/en-us/windows/security/windows-security/app-browser-control-in-the-windows-security-app',
    sourceLevel: 'official',
    sourceType: 'platform-support',
    accessedAt,
    notes: 'Official Windows guidance for Smart App Control modes, updates, security role, and version-dependent setting behavior.',
  },
  islandsGuide: {
    id: 'islands-guide',
    label: 'All islands and unlock route',
    publisher: 'Destructoid',
    url: 'https://www.destructoid.com/all-islands-coordinates-locations-how-to-fish/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Third-party route reference used to reconcile the Lighthouse plus four unlockable areas counting convention.',
  },
  tipsVideo: {
    id: 'tips-video',
    label: "10 Things the Game Doesn't Tell You",
    publisher: 'YouTube gameplay guide',
    url: 'https://www.youtube.com/watch?v=Mi94jv9ttWc',
    sourceLevel: 'community',
    sourceType: 'youtube',
    accessedAt,
    notes: 'Gameplay footage used to identify unclear systems; individual claims remain version-sensitive.',
  },
  bitingDiscussion: {
    id: 'fish-not-biting',
    label: 'Fish not biting discussion',
    publisher: 'How to Fish community on Reddit',
    url: 'https://www.reddit.com/r/HowToFish/comments/1vvglei/fish_not_biting/',
    sourceLevel: 'community',
    sourceType: 'reddit',
    accessedAt,
    notes: 'Player question used to define the reel/rod/lure troubleshooting checklist.',
  },
  audioDiscussion: {
    id: 'audio-glitch-discussion',
    label: 'Audio glitch issue report',
    publisher: 'Steam Community discussion',
    url: 'https://steamcommunity.com/app/4001890/discussions/0/581680664978521552/',
    sourceLevel: 'community',
    sourceType: 'steam-discussion',
    accessedAt,
    notes: 'Player reports about repeating or degraded audio; retained as a noindex evidence-threshold draft.',
  },
  bingBongGuide: {
    id: 'bing-bong-guide',
    label: 'Bing Bong catch guide',
    publisher: 'Pro Game Guides',
    url: 'https://progameguides.com/how-to-fish/how-to-fish-bing-bong-guide/',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Third-party report for the Desert Coconut route; exact price, exclusivity, and catch guarantee remain unverified here.',
  },
  cookingGuide: {
    id: 'cooking-guide',
    label: 'How to cook fish and unlock the grill',
    publisher: 'Mobalytics Gamebase',
    url: 'https://mobalytics.gg/gamebase/guides/how-to-fish-grill-guide',
    sourceLevel: 'community',
    sourceType: 'media-guide',
    accessedAt,
    notes: 'Third-party grill route and inspect-control observations; exact value windows remain unverified by this site.',
  },
  dazedGamesFaq: {
    id: 'dazed-games-platform-faq',
    label: 'Dazed Games platform FAQ',
    publisher: 'Dazed Games',
    url: 'https://dazed.games/',
    sourceLevel: 'official',
    sourceType: 'platform-support',
    accessedAt,
    notes: 'Developer says console and Mac versions are coming but gives no date; it does not identify Xbox, PlayStation, or mobile releases individually.',
  },
  steamDbConfig: {
    id: 'steamdb-app-configuration',
    label: 'How to Fish app configuration',
    publisher: 'SteamDB',
    url: 'https://steamdb.info/app/4001890/config/',
    sourceLevel: 'community',
    sourceType: 'platform-support',
    accessedAt,
    notes: 'Independent configuration mirror showing the current Windows executable; the official Steam store remains the platform authority.',
  },
  steamMedia: {
    id: 'steam-media',
    label: 'Official How to Fish screenshots',
    publisher: 'Dazed Games / Steam',
    url: 'https://store.steampowered.com/app/4001890/How_to_Fish/',
    sourceLevel: 'official',
    sourceType: 'steam-store',
    accessedAt,
    notes: 'Official promotional screenshots used for visual context, not as proof of exact route steps or values.',
  },
};

export function resolveSources(ids: string[]) {
  return ids.map((id) => sources[id]).filter(Boolean);
}
